package Controller;

import java.net.URL;
import java.util.ResourceBundle;

import javax.swing.JOptionPane;

import Connection.ConnectionMySQL;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.ChoiceBox;
import javafx.scene.control.TextField;

public class CoefficientController implements Initializable {
	@FXML
	private ChoiceBox<String> box;
	@FXML
	private TextField cc;
	@FXML
	private TextField tp;
	@FXML
	private TextField exam;
	@FXML
	private Button enregister;
	
	// Event Listener on Button[#enregister].onAction
		@FXML
		public void enregistrerClicked(ActionEvent event) throws NumberFormatException, Exception {
			// TODO Autogenerated
			try {
				if (cc.getText().equals("") || tp.getText().equals("") || exam.getText().equals("") || String.valueOf(box.getValue()).equals("")) {
					JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs!");
				}else {
				ConnectionMySQL x = new ConnectionMySQL();
				x.insererCoef(Float.parseFloat(cc.getText()), Float.parseFloat(tp.getText()), Float.parseFloat(exam.getText()),box.getValue());
				cc.setText(null);
				tp.setText(null);
				exam.setText(null);
				JOptionPane.showMessageDialog(null, "enregistrement bien fait !");
				}
			}catch(NumberFormatException e) {
				JOptionPane.showMessageDialog(null, "Valeurs invalides");
			}
			
		}

		@Override
		public void initialize(URL arg0, ResourceBundle arg1) {
			// TODO Auto-generated method stub
			ConnectionMySQL x = new ConnectionMySQL();
			try {
				box.getItems().addAll(x.matChoiceBox());
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
}


