package Controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;

import java.awt.Desktop;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javax.swing.JOptionPane;

import com.itextpdf.text.pdf.PdfDocument;
import com.itextpdf.text.pdf.PdfReader;
import com.itextpdf.text.pdf.parser.PdfTextExtractor;

import Class.Etudiant;
import Connection.ConnectionMySQL;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.control.ChoiceBox;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TableColumn;

public class CordiListeController implements Initializable{
	@FXML
	private TableView table;
	@FXML
	private TableColumn id;
	@FXML
	private TableColumn nom;
	@FXML
	private TableColumn prenom;
	@FXML
	private TableColumn semestre;
	@FXML
	private TableColumn filiere;
	@FXML
	private TableColumn module;
	@FXML
	private TableColumn validation;
	@FXML
	private ComboBox semestrechoix;
	


	// Event Listener on Button.onAction
	@FXML
	public void PDF(ActionEvent event) {
		// TODO Autogenerated
		ConnectionMySQL x = new ConnectionMySQL();
		try {
			if(String.valueOf(semestrechoix.getValue()).equals("")) {
				JOptionPane.showMessageDialog(null, "Veuillez selectionnez un semestre");
			}else {
				x.pdfs( String.valueOf(semestrechoix.getValue()));
				openPDF();
			}
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, "erreur !! ");

		}
		
	}
	
	
	// Event Listener on Button.onAction
	@FXML
	public void chercher(ActionEvent event) {
		// TODO Autogenerated
		ConnectionMySQL x = new ConnectionMySQL();
		ObservableList<Etudiant> y =null;
		String sem=(String) semestrechoix.getValue();
		y = x.listeEtudiantCordi(sem);
		table.setItems(y);
	}
	public void openPDF() {
		File file = new File("C:\\Users\\hp\\Desktop\\PV_note.pdf");    
		Desktop desktop = Desktop.getDesktop();  
			try {
				desktop.open(file);
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}              //opens the specified file    
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		ConnectionMySQL x = new ConnectionMySQL();
		try {
			semestrechoix.getItems().addAll(x.semChoiceBox());
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		table.getItems().clear();
		id. setCellValueFactory(new PropertyValueFactory<Etudiant, Integer>("id"));
		nom.setCellValueFactory(new PropertyValueFactory<Etudiant, String >("nom"));
		prenom.setCellValueFactory(new PropertyValueFactory<Etudiant, String>("prenom"));
		semestre.setCellValueFactory(new PropertyValueFactory<Etudiant, String>("semestre"));
		filiere.setCellValueFactory(new PropertyValueFactory<Etudiant, String>("filiere"));
		module.setCellValueFactory(new PropertyValueFactory<Etudiant, Float>("moyenne"));
		validation.setCellValueFactory(new PropertyValueFactory<Etudiant, Float>("Validation"));

	}
}


