package Controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;

import java.io.IOException;

import application.Main;
import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

public class CordiHomeController {
	@FXML
	private AnchorPane rootPane;

	// Event Listener on MenuItem.onAction
	@FXML
	public void profil(ActionEvent event) {
		// TODO Autogenerated
		try {
			rootPane.getChildren().clear();
			AnchorPane root = FXMLLoader.load(getClass().getResource("/Interface/CordiProfil.fxml"));
			rootPane.getChildren().addAll(root);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void bienvenue(ActionEvent event) {
		// TODO Autogenerated
		try {
			rootPane.getChildren().clear();
			AnchorPane root = FXMLLoader.load(getClass().getResource("/Interface/bienvenue .fxml"));
			rootPane.getChildren().addAll(root);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void etudiant(ActionEvent event) {
		// TODO Autogenerated
		try {
			rootPane.getChildren().clear();
			AnchorPane root = FXMLLoader.load(getClass().getResource("/Interface/CordiListe.fxml"));
			rootPane.getChildren().addAll(root);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void note(ActionEvent event) {
		// TODO Autogenerated
		try {
			rootPane.getChildren().clear();
			AnchorPane root = FXMLLoader.load(getClass().getResource("/Interface/CordiNote.fxml"));
			rootPane.getChildren().addAll(root);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void securite(ActionEvent event) {
		// TODO Autogenerated
		try {
			rootPane.getChildren().clear();
			AnchorPane root = FXMLLoader.load(getClass().getResource("/Interface/securite.fxml"));
			rootPane.getChildren().addAll(root);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void deco(ActionEvent event) {
		// TODO Autogenerated
		Main m = new Main();
		try {
			m.changeScene("/Interface/Login.fxml");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void quitter(ActionEvent event) {
		// TODO Autogenerated
		System.exit(0);
	}
}



