package Controller;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javax.swing.JOptionPane;

import Connection.ConnectionMySQL;
import application.Main;
import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class LoginController {
	@FXML
	private TextField id;
	@FXML
	private PasswordField idd;

	// Event Listener on Button.onAction
	@FXML
	public void loginClicked(ActionEvent event) {
		// TODO Autogenerated
		Main m =new Main();
		ConnectionMySQL x = new  Connection.ConnectionMySQL();
		try {
			String con = x.testConnection(id.getText(), idd.getText());
			if(con==null) {
				JOptionPane.showMessageDialog(null, "veuillez vérifier vos données saisies merci ");
				idd.setText(null);
			}else if(con.equals("Coordinateur")) {
				m.changeScene("/Interface/CordiHome.fxml");
			} else if(con.equals("Professeur")){
				m.changeScene("/Interface/ProfHome.fxml");
			} else if(con.equals("Administrateur")) {
				m.changeScene("/Interface/AdminHome.fxml");
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}


