package Controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.TextField;

import java.net.URL;
import java.util.ArrayList;
import java.util.ResourceBundle;

import javax.swing.JOptionPane;

import Class.Etudiant;
import Connection.ConnectionMySQL;
import javafx.event.ActionEvent;
import javafx.scene.control.Button;
import javafx.scene.control.ChoiceBox;

public class ModifierEtudController implements Initializable {
	@FXML
	private TextField id;
	@FXML
	private TextField nom;
	@FXML
	private TextField prenom;
	@FXML
	private ChoiceBox filiere;
	@FXML
	private ChoiceBox semestre;
	@FXML
	private Button modifierBtn;

	// Event Listener on Button.onAction
	@FXML
	public void modifier(ActionEvent event) {
		// TODO Autogenerated
		ConnectionMySQL x = new ConnectionMySQL();
		x.ModifierEtud(Integer.parseInt(id.getText()), nom.getText(), prenom.getText(), String.valueOf(filiere.getValue()), String.valueOf(semestre.getValue()));
		JOptionPane.showMessageDialog(null, "Mis à jour avec succés ");

	}
	// Event Listener on Button.onAction
	@FXML
	public void chercher(ActionEvent event) {
		// TODO Autogenerated
		ConnectionMySQL x = new ConnectionMySQL();
		ArrayList<Etudiant> y = x.chercherEtud(Integer.parseInt(id.getText()));
		if(y.isEmpty()) {
			JOptionPane.showMessageDialog(null, "Aucun Etudiant");
		}else {
			nom.setText(y.get(0).getNom());
			nom.setDisable(false);
			prenom.setText(y.get(0).getPrenom());
			prenom.setDisable(false);
			filiere.setValue(y.get(0).getFiliere());
			filiere.setDisable(false);
			semestre.setValue(y.get(0).getSemestre());
			semestre.setDisable(false);
			modifierBtn.setDisable(false);
		}

	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		ConnectionMySQL x = new ConnectionMySQL();
		try {
			filiere.getItems().addAll(x.filChoiceBox());
			semestre.getItems().addAll(x.semChoiceBox());

		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}


