package Controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;

import java.io.IOException;

import application.Main;
import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

public class ProfHomeController {
	@FXML
	private AnchorPane rootPane;

	// Event Listener on MenuItem.onAction
	@FXML
	public void profil(ActionEvent event) {
		// TODO Autogenerated
		try {
			rootPane.getChildren().clear();
			AnchorPane root = FXMLLoader.load(getClass().getResource("/Interface/ProfProfil.fxml"));
			rootPane.getChildren().addAll(root);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void bienvenue(ActionEvent event) {
		// TODO Autogenerated
		try {
			rootPane.getChildren().clear();
			AnchorPane root = FXMLLoader.load(getClass().getResource("/Interface/Bienvenue .fxml"));
			rootPane.getChildren().addAll(root);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void etudiant(ActionEvent event) {
		// TODO Autogenerated
		try {
			rootPane.getChildren().clear();
			AnchorPane root = FXMLLoader.load(getClass().getResource("/Interface/ListeEtudiant.fxml"));
			rootPane.getChildren().addAll(root);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void matiere(ActionEvent event) {
		// TODO Autogenerated
		try {
			rootPane.getChildren().clear();
			AnchorPane root = FXMLLoader.load(getClass().getResource("/Interface/ListeMatiere.fxml"));
			rootPane.getChildren().addAll(root);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void notes(ActionEvent event) {
		// TODO Autogenerated
		try {
			rootPane.getChildren().clear();
			AnchorPane root = FXMLLoader.load(getClass().getResource("/Interface/NoteEtudiant.fxml"));
			rootPane.getChildren().addAll(root);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void coef(ActionEvent event) {
		// TODO Autogenerated
		try {
			rootPane.getChildren().clear();
			AnchorPane root = FXMLLoader.load(getClass().getResource("/Interface/Coefficient.fxml"));
			rootPane.getChildren().addAll(root);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void securite(ActionEvent event) {
		// TODO Autogenerated
		try {
			rootPane.getChildren().clear();
			AnchorPane root = FXMLLoader.load(getClass().getResource("/Interface/securite.fxml"));
			rootPane.getChildren().addAll(root);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void deco(ActionEvent event) {
		// TODO Autogenerated
		Main m = new Main();
		try {
			m.changeScene("/Interface/Login.fxml");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void quitter(ActionEvent event) {
		// TODO Autogenerated
		System.exit(0);
	}
}


