package Controller;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import java.util.ArrayList;

import javax.swing.JOptionPane;

import Class.Etudiant;
import Connection.ConnectionMySQL;
import javafx.event.ActionEvent;
import javafx.scene.control.Button;
import javafx.scene.control.Label;

public class SupprimerEtudController {
	@FXML
	private TextField id;
	@FXML
	private Label nom;
	@FXML
	private Label semestre;
	@FXML
	private Label prenom;
	@FXML
	private Label filiere;
	@FXML
	private Button supprimer;

	// Event Listener on Button.onAction
		@FXML
		public void supprimer(ActionEvent event) {
			// TODO Autogenerated
			ConnectionMySQL x = new ConnectionMySQL();
			x.SupprimerEtud(Integer.parseInt(id.getText()));
			JOptionPane.showMessageDialog(null, "Suppression bien fait ");

		}
		// Event Listener on Button.onAction
		@FXML
		public void chercher(ActionEvent event) {
			// TODO Autogenerated
			ConnectionMySQL x = new ConnectionMySQL();
			ArrayList<Etudiant> y = x.chercherEtud(Integer.parseInt(id.getText()));
			if(y.isEmpty()) {
				JOptionPane.showMessageDialog(null, "Aucun Etudiant");
			}else {
				nom.setText(y.get(0).getNom());
				prenom.setText(y.get(0).getPrenom());
				filiere.setText(y.get(0).getFiliere());
				semestre.setText(y.get(0).getSemestre());
				supprimer.setDisable(false);
			}
			
		}
	}
